// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Exoscale
{
    /// <summary>
    /// Provides an Exoscale [SSH Keypair][ssh-keypairs-doc] resource. This can be used to create and delete SSH Keypairs.
    /// 
    /// !&gt; **WARNING:** This resource is deprecated and will be removed in the next major version.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Exoscale = Pulumi.Exoscale;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var admin = new Exoscale.SSHKeyPair("admin", new Exoscale.SSHKeyPairArgs
    ///         {
    ///             PublicKey = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGRY...",
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// 
    /// ## Import
    /// 
    /// An existing SSH Keypair can be imported as a resource by nameconsole
    /// 
    /// ```sh
    ///  $ pulumi import exoscale:index/sSHKeyPair:SSHKeyPair mykey my-key
    /// ```
    /// 
    ///  [ssh-keypairs-doc]https://community.exoscale.com/documentation/compute/ssh-keypairs/
    /// </summary>
    [ExoscaleResourceType("exoscale:index/sSHKeyPair:SSHKeyPair")]
    public partial class SSHKeyPair : Pulumi.CustomResource
    {
        /// <summary>
        /// The unique identifier of the SSH Keypair.
        /// </summary>
        [Output("fingerprint")]
        public Output<string> Fingerprint { get; private set; } = null!;

        /// <summary>
        /// The name of the SSH Keypair.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The SSH private key generated if no public key was provided.
        /// </summary>
        [Output("privateKey")]
        public Output<string> PrivateKey { get; private set; } = null!;

        /// <summary>
        /// A SSH public key that will be copied into the instances at **first** boot. If not provided, a SSH keypair is generated and the is saved locally (see the `private_key` attribute).
        /// </summary>
        [Output("publicKey")]
        public Output<string?> PublicKey { get; private set; } = null!;


        /// <summary>
        /// Create a SSHKeyPair resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SSHKeyPair(string name, SSHKeyPairArgs? args = null, CustomResourceOptions? options = null)
            : base("exoscale:index/sSHKeyPair:SSHKeyPair", name, args ?? new SSHKeyPairArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SSHKeyPair(string name, Input<string> id, SSHKeyPairState? state = null, CustomResourceOptions? options = null)
            : base("exoscale:index/sSHKeyPair:SSHKeyPair", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SSHKeyPair resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SSHKeyPair Get(string name, Input<string> id, SSHKeyPairState? state = null, CustomResourceOptions? options = null)
        {
            return new SSHKeyPair(name, id, state, options);
        }
    }

    public sealed class SSHKeyPairArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the SSH Keypair.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// A SSH public key that will be copied into the instances at **first** boot. If not provided, a SSH keypair is generated and the is saved locally (see the `private_key` attribute).
        /// </summary>
        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        public SSHKeyPairArgs()
        {
        }
    }

    public sealed class SSHKeyPairState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The unique identifier of the SSH Keypair.
        /// </summary>
        [Input("fingerprint")]
        public Input<string>? Fingerprint { get; set; }

        /// <summary>
        /// The name of the SSH Keypair.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The SSH private key generated if no public key was provided.
        /// </summary>
        [Input("privateKey")]
        public Input<string>? PrivateKey { get; set; }

        /// <summary>
        /// A SSH public key that will be copied into the instances at **first** boot. If not provided, a SSH keypair is generated and the is saved locally (see the `private_key` attribute).
        /// </summary>
        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        public SSHKeyPairState()
        {
        }
    }
}
