// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Exoscale.Outputs
{

    [OutputType]
    public sealed class GetDomainRecordFilterResult
    {
        /// <summary>
        /// A regular expression matching the domain record content to lookup.
        /// </summary>
        public readonly string? ContentRegex;
        /// <summary>
        /// The ID matching the domain record ID to lookup.
        /// </summary>
        public readonly int? Id;
        /// <summary>
        /// The name matching the domain record name to lookup.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The record type matching the domain record type to lookup.
        /// </summary>
        public readonly string? RecordType;

        [OutputConstructor]
        private GetDomainRecordFilterResult(
            string? contentRegex,

            int? id,

            string? name,

            string? recordType)
        {
            ContentRegex = contentRegex;
            Id = id;
            Name = name;
            RecordType = recordType;
        }
    }
}
