# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ElasticIPArgs', 'ElasticIP']

@pulumi.input_type
class ElasticIPArgs:
    def __init__(__self__, *,
                 zone: pulumi.Input[str],
                 description: Optional[pulumi.Input[str]] = None,
                 healthcheck: Optional[pulumi.Input['ElasticIPHealthcheckArgs']] = None):
        """
        The set of arguments for constructing a ElasticIP resource.
        :param pulumi.Input[str] zone: The name of the [zone][zone] to create the Elastic IP into.
        :param pulumi.Input[str] description: The description of the Elastic IP.
        :param pulumi.Input['ElasticIPHealthcheckArgs'] healthcheck: A health checking configuration for managed Elastic IPs. Structure is documented below.
        """
        pulumi.set(__self__, "zone", zone)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if healthcheck is not None:
            pulumi.set(__self__, "healthcheck", healthcheck)

    @property
    @pulumi.getter
    def zone(self) -> pulumi.Input[str]:
        """
        The name of the [zone][zone] to create the Elastic IP into.
        """
        return pulumi.get(self, "zone")

    @zone.setter
    def zone(self, value: pulumi.Input[str]):
        pulumi.set(self, "zone", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        The description of the Elastic IP.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter
    def healthcheck(self) -> Optional[pulumi.Input['ElasticIPHealthcheckArgs']]:
        """
        A health checking configuration for managed Elastic IPs. Structure is documented below.
        """
        return pulumi.get(self, "healthcheck")

    @healthcheck.setter
    def healthcheck(self, value: Optional[pulumi.Input['ElasticIPHealthcheckArgs']]):
        pulumi.set(self, "healthcheck", value)


@pulumi.input_type
class _ElasticIPState:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[str]] = None,
                 healthcheck: Optional[pulumi.Input['ElasticIPHealthcheckArgs']] = None,
                 ip_address: Optional[pulumi.Input[str]] = None,
                 zone: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering ElasticIP resources.
        :param pulumi.Input[str] description: The description of the Elastic IP.
        :param pulumi.Input['ElasticIPHealthcheckArgs'] healthcheck: A health checking configuration for managed Elastic IPs. Structure is documented below.
        :param pulumi.Input[str] ip_address: The Elastic IP address.
        :param pulumi.Input[str] zone: The name of the [zone][zone] to create the Elastic IP into.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if healthcheck is not None:
            pulumi.set(__self__, "healthcheck", healthcheck)
        if ip_address is not None:
            pulumi.set(__self__, "ip_address", ip_address)
        if zone is not None:
            pulumi.set(__self__, "zone", zone)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        The description of the Elastic IP.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter
    def healthcheck(self) -> Optional[pulumi.Input['ElasticIPHealthcheckArgs']]:
        """
        A health checking configuration for managed Elastic IPs. Structure is documented below.
        """
        return pulumi.get(self, "healthcheck")

    @healthcheck.setter
    def healthcheck(self, value: Optional[pulumi.Input['ElasticIPHealthcheckArgs']]):
        pulumi.set(self, "healthcheck", value)

    @property
    @pulumi.getter(name="ipAddress")
    def ip_address(self) -> Optional[pulumi.Input[str]]:
        """
        The Elastic IP address.
        """
        return pulumi.get(self, "ip_address")

    @ip_address.setter
    def ip_address(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "ip_address", value)

    @property
    @pulumi.getter
    def zone(self) -> Optional[pulumi.Input[str]]:
        """
        The name of the [zone][zone] to create the Elastic IP into.
        """
        return pulumi.get(self, "zone")

    @zone.setter
    def zone(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "zone", value)


class ElasticIP(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 healthcheck: Optional[pulumi.Input[pulumi.InputType['ElasticIPHealthcheckArgs']]] = None,
                 zone: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Provides an Exoscale [Elastic IP address][eip-doc] resource. This can be used to create, update and delete Elastic IPs.

        ## Import

        An existing Elastic IP can be imported as a resource by specifying `ID@ZONE`console

        ```sh
         $ pulumi import exoscale:index/elasticIP:ElasticIP web eb556678-ec59-4be6-8c54-0406ae0f6da6@ch-dk-2
        ```

         [eip-doc]https://community.exoscale.com/documentation/compute/eip/ [zone]https://www.exoscale.com/datacenters/

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] description: The description of the Elastic IP.
        :param pulumi.Input[pulumi.InputType['ElasticIPHealthcheckArgs']] healthcheck: A health checking configuration for managed Elastic IPs. Structure is documented below.
        :param pulumi.Input[str] zone: The name of the [zone][zone] to create the Elastic IP into.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ElasticIPArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Provides an Exoscale [Elastic IP address][eip-doc] resource. This can be used to create, update and delete Elastic IPs.

        ## Import

        An existing Elastic IP can be imported as a resource by specifying `ID@ZONE`console

        ```sh
         $ pulumi import exoscale:index/elasticIP:ElasticIP web eb556678-ec59-4be6-8c54-0406ae0f6da6@ch-dk-2
        ```

         [eip-doc]https://community.exoscale.com/documentation/compute/eip/ [zone]https://www.exoscale.com/datacenters/

        :param str resource_name: The name of the resource.
        :param ElasticIPArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ElasticIPArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 healthcheck: Optional[pulumi.Input[pulumi.InputType['ElasticIPHealthcheckArgs']]] = None,
                 zone: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ElasticIPArgs.__new__(ElasticIPArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["healthcheck"] = healthcheck
            if zone is None and not opts.urn:
                raise TypeError("Missing required property 'zone'")
            __props__.__dict__["zone"] = zone
            __props__.__dict__["ip_address"] = None
        super(ElasticIP, __self__).__init__(
            'exoscale:index/elasticIP:ElasticIP',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: Optional[pulumi.Input[str]] = None,
            healthcheck: Optional[pulumi.Input[pulumi.InputType['ElasticIPHealthcheckArgs']]] = None,
            ip_address: Optional[pulumi.Input[str]] = None,
            zone: Optional[pulumi.Input[str]] = None) -> 'ElasticIP':
        """
        Get an existing ElasticIP resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] description: The description of the Elastic IP.
        :param pulumi.Input[pulumi.InputType['ElasticIPHealthcheckArgs']] healthcheck: A health checking configuration for managed Elastic IPs. Structure is documented below.
        :param pulumi.Input[str] ip_address: The Elastic IP address.
        :param pulumi.Input[str] zone: The name of the [zone][zone] to create the Elastic IP into.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ElasticIPState.__new__(_ElasticIPState)

        __props__.__dict__["description"] = description
        __props__.__dict__["healthcheck"] = healthcheck
        __props__.__dict__["ip_address"] = ip_address
        __props__.__dict__["zone"] = zone
        return ElasticIP(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[str]]:
        """
        The description of the Elastic IP.
        """
        return pulumi.get(self, "description")

    @property
    @pulumi.getter
    def healthcheck(self) -> pulumi.Output['outputs.ElasticIPHealthcheck']:
        """
        A health checking configuration for managed Elastic IPs. Structure is documented below.
        """
        return pulumi.get(self, "healthcheck")

    @property
    @pulumi.getter(name="ipAddress")
    def ip_address(self) -> pulumi.Output[str]:
        """
        The Elastic IP address.
        """
        return pulumi.get(self, "ip_address")

    @property
    @pulumi.getter
    def zone(self) -> pulumi.Output[str]:
        """
        The name of the [zone][zone] to create the Elastic IP into.
        """
        return pulumi.get(self, "zone")

