# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetSecurityGroupResult',
    'AwaitableGetSecurityGroupResult',
    'get_security_group',
    'get_security_group_output',
]

@pulumi.output_type
class GetSecurityGroupResult:
    """
    A collection of values returned by getSecurityGroup.
    """
    def __init__(__self__, id=None, name=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def id(self) -> Optional[str]:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> Optional[str]:
        return pulumi.get(self, "name")


class AwaitableGetSecurityGroupResult(GetSecurityGroupResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSecurityGroupResult(
            id=self.id,
            name=self.name)


def get_security_group(id: Optional[str] = None,
                       name: Optional[str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSecurityGroupResult:
    """
    Provides information on a [Security Group][sg-doc] for use in other resources such as a [`InstancePool`][r-instance_pool] resource.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_exoscale as exoscale

    zone = "ch-gva-2"
    web = exoscale.get_security_group(name="web")
    ubuntu = exoscale.get_compute_template(zone=zone,
        name="Linux Ubuntu 20.04 LTS 64-bit")
    webservers = exoscale.InstancePool("webservers",
        zone=zone,
        template_id=ubuntu.id,
        size=5,
        service_offering="medium",
        security_group_ids=[web.id])
    ```


    :param str id: The ID of the Security Group (conflicts with `name`)
    :param str name: The name of the Security Group (conflicts with `id`)
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
    __ret__ = pulumi.runtime.invoke('exoscale:index/getSecurityGroup:getSecurityGroup', __args__, opts=opts, typ=GetSecurityGroupResult).value

    return AwaitableGetSecurityGroupResult(
        id=__ret__.id,
        name=__ret__.name)


@_utilities.lift_output_func(get_security_group)
def get_security_group_output(id: Optional[pulumi.Input[Optional[str]]] = None,
                              name: Optional[pulumi.Input[Optional[str]]] = None,
                              opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetSecurityGroupResult]:
    """
    Provides information on a [Security Group][sg-doc] for use in other resources such as a [`InstancePool`][r-instance_pool] resource.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_exoscale as exoscale

    zone = "ch-gva-2"
    web = exoscale.get_security_group(name="web")
    ubuntu = exoscale.get_compute_template(zone=zone,
        name="Linux Ubuntu 20.04 LTS 64-bit")
    webservers = exoscale.InstancePool("webservers",
        zone=zone,
        template_id=ubuntu.id,
        size=5,
        service_offering="medium",
        security_group_ids=[web.id])
    ```


    :param str id: The ID of the Security Group (conflicts with `name`)
    :param str name: The name of the Security Group (conflicts with `id`)
    """
    ...
