// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package exoscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides information on a [Private Network][privnet-doc] for use in other resources such as a [`InstancePool`][r-instance_pool] resource.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-exoscale/sdk/go/exoscale"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		zone := "ch-gva-2"
// 		opt0 := "db"
// 		db, err := exoscale.LookupPrivateNetwork(ctx, &GetPrivateNetworkArgs{
// 			Zone: zone,
// 			Name: &opt0,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		opt1 := "Linux Ubuntu 20.04 LTS 64-bit"
// 		ubuntu, err := exoscale.GetComputeTemplate(ctx, &GetComputeTemplateArgs{
// 			Zone: zone,
// 			Name: &opt1,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		_, err = exoscale.NewInstancePool(ctx, "webservers", &exoscale.InstancePoolArgs{
// 			Zone:            pulumi.String(zone),
// 			TemplateId:      pulumi.String(ubuntu.Id),
// 			Size:            pulumi.Int(5),
// 			ServiceOffering: pulumi.String("standard.medium"),
// 			NetworkIds: pulumi.StringArray{
// 				pulumi.String(db.Id),
// 			},
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupPrivateNetwork(ctx *pulumi.Context, args *LookupPrivateNetworkArgs, opts ...pulumi.InvokeOption) (*LookupPrivateNetworkResult, error) {
	var rv LookupPrivateNetworkResult
	err := ctx.Invoke("exoscale:index/getPrivateNetwork:getPrivateNetwork", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPrivateNetwork.
type LookupPrivateNetworkArgs struct {
	// The description of the Private Network.
	Description *string `pulumi:"description"`
	// The ID of the Private Network (conflicts with `name`).
	Id *string `pulumi:"id"`
	// The name of the Private Network (conflicts with `id`).
	Name *string `pulumi:"name"`
	// The [zone][zone] of the Private Network.
	Zone string `pulumi:"zone"`
}

// A collection of values returned by getPrivateNetwork.
type LookupPrivateNetworkResult struct {
	// The description of the Private Network.
	Description *string `pulumi:"description"`
	// The last address of the IP range used by the DHCP service (for *managed* Private Networks).
	EndIp string  `pulumi:"endIp"`
	Id    *string `pulumi:"id"`
	Name  *string `pulumi:"name"`
	// The netmask defining the IP network allowed for the static lease (for *managed* Private Networks).
	Netmask string `pulumi:"netmask"`
	// The first address of IP range used by the DHCP service to automatically assign (for *managed* Private Networks).
	StartIp string `pulumi:"startIp"`
	Zone    string `pulumi:"zone"`
}

func LookupPrivateNetworkOutput(ctx *pulumi.Context, args LookupPrivateNetworkOutputArgs, opts ...pulumi.InvokeOption) LookupPrivateNetworkResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupPrivateNetworkResult, error) {
			args := v.(LookupPrivateNetworkArgs)
			r, err := LookupPrivateNetwork(ctx, &args, opts...)
			return *r, err
		}).(LookupPrivateNetworkResultOutput)
}

// A collection of arguments for invoking getPrivateNetwork.
type LookupPrivateNetworkOutputArgs struct {
	// The description of the Private Network.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The ID of the Private Network (conflicts with `name`).
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The name of the Private Network (conflicts with `id`).
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The [zone][zone] of the Private Network.
	Zone pulumi.StringInput `pulumi:"zone"`
}

func (LookupPrivateNetworkOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPrivateNetworkArgs)(nil)).Elem()
}

// A collection of values returned by getPrivateNetwork.
type LookupPrivateNetworkResultOutput struct{ *pulumi.OutputState }

func (LookupPrivateNetworkResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPrivateNetworkResult)(nil)).Elem()
}

func (o LookupPrivateNetworkResultOutput) ToLookupPrivateNetworkResultOutput() LookupPrivateNetworkResultOutput {
	return o
}

func (o LookupPrivateNetworkResultOutput) ToLookupPrivateNetworkResultOutputWithContext(ctx context.Context) LookupPrivateNetworkResultOutput {
	return o
}

// The description of the Private Network.
func (o LookupPrivateNetworkResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupPrivateNetworkResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The last address of the IP range used by the DHCP service (for *managed* Private Networks).
func (o LookupPrivateNetworkResultOutput) EndIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateNetworkResult) string { return v.EndIp }).(pulumi.StringOutput)
}

func (o LookupPrivateNetworkResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupPrivateNetworkResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

func (o LookupPrivateNetworkResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupPrivateNetworkResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// The netmask defining the IP network allowed for the static lease (for *managed* Private Networks).
func (o LookupPrivateNetworkResultOutput) Netmask() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateNetworkResult) string { return v.Netmask }).(pulumi.StringOutput)
}

// The first address of IP range used by the DHCP service to automatically assign (for *managed* Private Networks).
func (o LookupPrivateNetworkResultOutput) StartIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateNetworkResult) string { return v.StartIp }).(pulumi.StringOutput)
}

func (o LookupPrivateNetworkResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateNetworkResult) string { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupPrivateNetworkResultOutput{})
}
