// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides an Exoscale [Anti-Affinity Group][aag-doc] resource. This can be used to create and delete Anti-Affinity Groups.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as exoscale from "@pulumi/exoscale";
 *
 * const example = new exoscale.AntiAffinityGroup("example", {
 *     description: "HA Cluster",
 * });
 * ```
 *
 * ## Import
 *
 * An existing Anti-Affinity Group can be imported as a resource its IDconsole
 *
 * ```sh
 *  $ pulumi import exoscale:index/antiAffinityGroup:AntiAffinityGroup my-group eb556678-ec59-4be6-8c54-0406ae0f6da6
 * ```
 *
 *  [aag-doc]https://community.exoscale.com/documentation/compute/anti-affinity-groups/
 */
export class AntiAffinityGroup extends pulumi.CustomResource {
    /**
     * Get an existing AntiAffinityGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AntiAffinityGroupState, opts?: pulumi.CustomResourceOptions): AntiAffinityGroup {
        return new AntiAffinityGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'exoscale:index/antiAffinityGroup:AntiAffinityGroup';

    /**
     * Returns true if the given object is an instance of AntiAffinityGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AntiAffinityGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AntiAffinityGroup.__pulumiType;
    }

    /**
     * An Anti-Affinity Group description.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The name of the Anti-Affinity Group.
     */
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a AntiAffinityGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AntiAffinityGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AntiAffinityGroupArgs | AntiAffinityGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AntiAffinityGroupState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as AntiAffinityGroupArgs | undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AntiAffinityGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AntiAffinityGroup resources.
 */
export interface AntiAffinityGroupState {
    /**
     * An Anti-Affinity Group description.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the Anti-Affinity Group.
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AntiAffinityGroup resource.
 */
export interface AntiAffinityGroupArgs {
    /**
     * An Anti-Affinity Group description.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the Anti-Affinity Group.
     */
    name?: pulumi.Input<string>;
}
