// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides an Exoscale [Compute instance][compute-doc] resource. This can be used to create, modify, and delete Compute instances.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as exoscale from "@pulumi/exoscale";
 *
 * const zone = "ch-gva-2";
 * const ubuntu = exoscale.getComputeTemplate({
 *     zone: zone,
 *     name: "Linux Ubuntu 20.04 LTS 64-bit",
 * });
 * const web = new exoscale.SecurityGroup("web", {});
 * const default = exoscale.getSecurityGroup({
 *     name: "default",
 * });
 * const example = new exoscale.ComputeInstance("example", {
 *     zone: zone,
 *     type: "standard.medium",
 *     templateId: ubuntu.then(ubuntu => ubuntu.id),
 *     diskSize: 10,
 *     securityGroupIds: [
 *         _default.then(_default => _default.id),
 *         web.id,
 *     ],
 *     sshKey: "my-key",
 *     userData: `#cloud-config
 * manage_etc_hosts: localhost
 * `,
 * });
 * ```
 *
 * ## Import
 *
 * An existing Compute instance can be imported as a resource by `<ID>@<ZONE>`console
 *
 * ```sh
 *  $ pulumi import exoscale:index/computeInstance:ComputeInstance my-instance eb556678-ec59-4be6-8c54-0406ae0f6da6@ch-gva-2
 * ```
 *
 *  [cloudinit]http://cloudinit.readthedocs.io/en/latest/ [compute-doc]https://community.exoscale.com/documentation/compute/ [d-anti_affinity_group]../d/anti_affinity_group.html [d-compute_template]../d/compute_template.html [d-elastic_ip]../d/elastic_ip.html [d-private_network]../d/private_network.html [d-security_group]../d/security_group.html [r-anti_affinity_group]anti_affinity_group.html [r-elastic_ip]../r/elastic_ip.html [r-private_network]../r/private_network.html [r-security_group]security_group.html [remote-exec]https://www.terraform.io/docs/provisioners/remote-exec.html [sshkeypair-doc]https://community.exoscale.com/documentation/compute/ssh-keypairs/ [template]https://www.exoscale.com/templates/ [type]https://www.exoscale.com/pricing/#/compute/ [zone]https://www.exoscale.com/datacenters/
 */
export class ComputeInstance extends pulumi.CustomResource {
    /**
     * Get an existing ComputeInstance resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ComputeInstanceState, opts?: pulumi.CustomResourceOptions): ComputeInstance {
        return new ComputeInstance(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'exoscale:index/computeInstance:ComputeInstance';

    /**
     * Returns true if the given object is an instance of ComputeInstance.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ComputeInstance {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ComputeInstance.__pulumiType;
    }

    /**
     * A list of [Anti-Affinity Group][r-anti_affinity_group] IDs (at creation time only) to assign the Compute instance. Usage of the [`exoscale.AntiAffinityGroup`][d-anti_affinity_group] data source is recommended.
     */
    public readonly antiAffinityGroupIds!: pulumi.Output<string[] | undefined>;
    /**
     * The creation date of the Compute instance.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * A Deploy Target ID.
     */
    public readonly deployTargetId!: pulumi.Output<string | undefined>;
    /**
     * The Compute instance disk size in GiB (at least `10`). **WARNING**: updating this attribute stops/restarts the Compute instance.
     */
    public readonly diskSize!: pulumi.Output<number>;
    /**
     * A list of [Elastic IP][r-elastic_ip] IDs to attach to the Compute instance. Usage of the [`exoscale.ElasticIP`][d-elastic_ip] data source is recommended.
     */
    public readonly elasticIpIds!: pulumi.Output<string[] | undefined>;
    /**
     * Enable IPv6 on the Compute instance (default: `false`).
     */
    public readonly ipv6!: pulumi.Output<boolean | undefined>;
    /**
     * The IPv6 address of the Compute instance main network interface.
     */
    public /*out*/ readonly ipv6Address!: pulumi.Output<string>;
    /**
     * A map of key/value labels.
     */
    public readonly labels!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The name of the Compute instance.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * A list of [Private Network][r-private_network] IDs to attach to the Compute instance. Usage of the [`exoscale.PrivateNetwork`][d-private_network] data source is recommended.
     */
    public readonly privateNetworkIds!: pulumi.Output<string[] | undefined>;
    /**
     * The IPv4 address of the Compute instance's main network interface.
     */
    public /*out*/ readonly publicIpAddress!: pulumi.Output<string>;
    /**
     * A list of [Security Group][r-security_group] IDs to attach to the Compute instance. Usage of the [`exoscale.SecurityGroup`][d-security_group] data source is recommended.
     */
    public readonly securityGroupIds!: pulumi.Output<string[] | undefined>;
    /**
     * The name of the [SSH key pair][sshkeypair] to install to the Compute instance's user account during creation.
     */
    public readonly sshKey!: pulumi.Output<string | undefined>;
    /**
     * The state of the Compute instance (supported values: `started`, `stopped`).
     */
    public readonly state!: pulumi.Output<string>;
    /**
     * The ID of the instance [template][template] to use when creating the Compute instance. Usage of the [`exoscale.getComputeTemplate`][d-compute_template] data source is recommended.
     */
    public readonly templateId!: pulumi.Output<string>;
    /**
     * The Compute instance [type][type] (format: `FAMILY.SIZE`, e.g. `standard.medium`, `memory.huge`).  **WARNING**: updating this attribute stops/restarts the Compute instance.
     */
    public readonly type!: pulumi.Output<string>;
    /**
     * A [cloud-init][cloudinit] configuration.
     */
    public readonly userData!: pulumi.Output<string | undefined>;
    /**
     * The name of the [zone][zone] to deploy the Compute instance into.
     */
    public readonly zone!: pulumi.Output<string>;

    /**
     * Create a ComputeInstance resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ComputeInstanceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ComputeInstanceArgs | ComputeInstanceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ComputeInstanceState | undefined;
            resourceInputs["antiAffinityGroupIds"] = state ? state.antiAffinityGroupIds : undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["deployTargetId"] = state ? state.deployTargetId : undefined;
            resourceInputs["diskSize"] = state ? state.diskSize : undefined;
            resourceInputs["elasticIpIds"] = state ? state.elasticIpIds : undefined;
            resourceInputs["ipv6"] = state ? state.ipv6 : undefined;
            resourceInputs["ipv6Address"] = state ? state.ipv6Address : undefined;
            resourceInputs["labels"] = state ? state.labels : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["privateNetworkIds"] = state ? state.privateNetworkIds : undefined;
            resourceInputs["publicIpAddress"] = state ? state.publicIpAddress : undefined;
            resourceInputs["securityGroupIds"] = state ? state.securityGroupIds : undefined;
            resourceInputs["sshKey"] = state ? state.sshKey : undefined;
            resourceInputs["state"] = state ? state.state : undefined;
            resourceInputs["templateId"] = state ? state.templateId : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
            resourceInputs["userData"] = state ? state.userData : undefined;
            resourceInputs["zone"] = state ? state.zone : undefined;
        } else {
            const args = argsOrState as ComputeInstanceArgs | undefined;
            if ((!args || args.templateId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'templateId'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            if ((!args || args.zone === undefined) && !opts.urn) {
                throw new Error("Missing required property 'zone'");
            }
            resourceInputs["antiAffinityGroupIds"] = args ? args.antiAffinityGroupIds : undefined;
            resourceInputs["deployTargetId"] = args ? args.deployTargetId : undefined;
            resourceInputs["diskSize"] = args ? args.diskSize : undefined;
            resourceInputs["elasticIpIds"] = args ? args.elasticIpIds : undefined;
            resourceInputs["ipv6"] = args ? args.ipv6 : undefined;
            resourceInputs["labels"] = args ? args.labels : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["privateNetworkIds"] = args ? args.privateNetworkIds : undefined;
            resourceInputs["securityGroupIds"] = args ? args.securityGroupIds : undefined;
            resourceInputs["sshKey"] = args ? args.sshKey : undefined;
            resourceInputs["state"] = args ? args.state : undefined;
            resourceInputs["templateId"] = args ? args.templateId : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["userData"] = args ? args.userData : undefined;
            resourceInputs["zone"] = args ? args.zone : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["ipv6Address"] = undefined /*out*/;
            resourceInputs["publicIpAddress"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ComputeInstance.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ComputeInstance resources.
 */
export interface ComputeInstanceState {
    /**
     * A list of [Anti-Affinity Group][r-anti_affinity_group] IDs (at creation time only) to assign the Compute instance. Usage of the [`exoscale.AntiAffinityGroup`][d-anti_affinity_group] data source is recommended.
     */
    antiAffinityGroupIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The creation date of the Compute instance.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * A Deploy Target ID.
     */
    deployTargetId?: pulumi.Input<string>;
    /**
     * The Compute instance disk size in GiB (at least `10`). **WARNING**: updating this attribute stops/restarts the Compute instance.
     */
    diskSize?: pulumi.Input<number>;
    /**
     * A list of [Elastic IP][r-elastic_ip] IDs to attach to the Compute instance. Usage of the [`exoscale.ElasticIP`][d-elastic_ip] data source is recommended.
     */
    elasticIpIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Enable IPv6 on the Compute instance (default: `false`).
     */
    ipv6?: pulumi.Input<boolean>;
    /**
     * The IPv6 address of the Compute instance main network interface.
     */
    ipv6Address?: pulumi.Input<string>;
    /**
     * A map of key/value labels.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the Compute instance.
     */
    name?: pulumi.Input<string>;
    /**
     * A list of [Private Network][r-private_network] IDs to attach to the Compute instance. Usage of the [`exoscale.PrivateNetwork`][d-private_network] data source is recommended.
     */
    privateNetworkIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The IPv4 address of the Compute instance's main network interface.
     */
    publicIpAddress?: pulumi.Input<string>;
    /**
     * A list of [Security Group][r-security_group] IDs to attach to the Compute instance. Usage of the [`exoscale.SecurityGroup`][d-security_group] data source is recommended.
     */
    securityGroupIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the [SSH key pair][sshkeypair] to install to the Compute instance's user account during creation.
     */
    sshKey?: pulumi.Input<string>;
    /**
     * The state of the Compute instance (supported values: `started`, `stopped`).
     */
    state?: pulumi.Input<string>;
    /**
     * The ID of the instance [template][template] to use when creating the Compute instance. Usage of the [`exoscale.getComputeTemplate`][d-compute_template] data source is recommended.
     */
    templateId?: pulumi.Input<string>;
    /**
     * The Compute instance [type][type] (format: `FAMILY.SIZE`, e.g. `standard.medium`, `memory.huge`).  **WARNING**: updating this attribute stops/restarts the Compute instance.
     */
    type?: pulumi.Input<string>;
    /**
     * A [cloud-init][cloudinit] configuration.
     */
    userData?: pulumi.Input<string>;
    /**
     * The name of the [zone][zone] to deploy the Compute instance into.
     */
    zone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ComputeInstance resource.
 */
export interface ComputeInstanceArgs {
    /**
     * A list of [Anti-Affinity Group][r-anti_affinity_group] IDs (at creation time only) to assign the Compute instance. Usage of the [`exoscale.AntiAffinityGroup`][d-anti_affinity_group] data source is recommended.
     */
    antiAffinityGroupIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A Deploy Target ID.
     */
    deployTargetId?: pulumi.Input<string>;
    /**
     * The Compute instance disk size in GiB (at least `10`). **WARNING**: updating this attribute stops/restarts the Compute instance.
     */
    diskSize?: pulumi.Input<number>;
    /**
     * A list of [Elastic IP][r-elastic_ip] IDs to attach to the Compute instance. Usage of the [`exoscale.ElasticIP`][d-elastic_ip] data source is recommended.
     */
    elasticIpIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Enable IPv6 on the Compute instance (default: `false`).
     */
    ipv6?: pulumi.Input<boolean>;
    /**
     * A map of key/value labels.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the Compute instance.
     */
    name?: pulumi.Input<string>;
    /**
     * A list of [Private Network][r-private_network] IDs to attach to the Compute instance. Usage of the [`exoscale.PrivateNetwork`][d-private_network] data source is recommended.
     */
    privateNetworkIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A list of [Security Group][r-security_group] IDs to attach to the Compute instance. Usage of the [`exoscale.SecurityGroup`][d-security_group] data source is recommended.
     */
    securityGroupIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the [SSH key pair][sshkeypair] to install to the Compute instance's user account during creation.
     */
    sshKey?: pulumi.Input<string>;
    /**
     * The state of the Compute instance (supported values: `started`, `stopped`).
     */
    state?: pulumi.Input<string>;
    /**
     * The ID of the instance [template][template] to use when creating the Compute instance. Usage of the [`exoscale.getComputeTemplate`][d-compute_template] data source is recommended.
     */
    templateId: pulumi.Input<string>;
    /**
     * The Compute instance [type][type] (format: `FAMILY.SIZE`, e.g. `standard.medium`, `memory.huge`).  **WARNING**: updating this attribute stops/restarts the Compute instance.
     */
    type: pulumi.Input<string>;
    /**
     * A [cloud-init][cloudinit] configuration.
     */
    userData?: pulumi.Input<string>;
    /**
     * The name of the [zone][zone] to deploy the Compute instance into.
     */
    zone: pulumi.Input<string>;
}
