// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides information on a Compute [Elastic IP address][eip-doc].
 *
 * !> **WARNING:** This data source is deprecated and will be removed in the next major version.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as exoscale from "@pulumi/exoscale";
 *
 * const zone = "ch-gva-2";
 * const eip = exoscale.getComputeIPAddress({
 *     zone: zone,
 *     ipAddress: "159.162.3.4",
 * });
 * ```
 */
export function getComputeIPAddress(args: GetComputeIPAddressArgs, opts?: pulumi.InvokeOptions): Promise<GetComputeIPAddressResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("exoscale:index/getComputeIPAddress:getComputeIPAddress", {
        "description": args.description,
        "id": args.id,
        "ipAddress": args.ipAddress,
        "tags": args.tags,
        "zone": args.zone,
    }, opts);
}

/**
 * A collection of arguments for invoking getComputeIPAddress.
 */
export interface GetComputeIPAddressArgs {
    /**
     * The Description to find the IP Address.
     */
    description?: string;
    /**
     * The ID of the IP Address.
     */
    id?: string;
    /**
     * The IP Address of the EIP.
     */
    ipAddress?: string;
    /**
     * The tags to find the IP Address.
     */
    tags?: {[key: string]: string};
    /**
     * The name of the [zone][zone] where to look for the IP Address.
     */
    zone: string;
}

/**
 * A collection of values returned by getComputeIPAddress.
 */
export interface GetComputeIPAddressResult {
    readonly description?: string;
    readonly id?: string;
    readonly ipAddress?: string;
    readonly tags?: {[key: string]: string};
    readonly zone: string;
}

export function getComputeIPAddressOutput(args: GetComputeIPAddressOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetComputeIPAddressResult> {
    return pulumi.output(args).apply(a => getComputeIPAddress(a, opts))
}

/**
 * A collection of arguments for invoking getComputeIPAddress.
 */
export interface GetComputeIPAddressOutputArgs {
    /**
     * The Description to find the IP Address.
     */
    description?: pulumi.Input<string>;
    /**
     * The ID of the IP Address.
     */
    id?: pulumi.Input<string>;
    /**
     * The IP Address of the EIP.
     */
    ipAddress?: pulumi.Input<string>;
    /**
     * The tags to find the IP Address.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the [zone][zone] where to look for the IP Address.
     */
    zone: pulumi.Input<string>;
}
